#if !defined(LS_ERRORS_H)
#define LS_ERRORS_H

#include "cbase.h"

#define ENUM_NAME LsError
#define ENUM_BITFLAGS 0
#define ENUM_PREFIX_ LS_ERROR_
#define ENUM_FIELDS \
    XX(LS_ERROR_NONE) \
    XX(LS_ERROR_PARSE_INVALID_ARGUMENT) \
    XX(LS_ERROR_PARSE_TOO_LARGE) \
    XX(LS_ERROR_PARSE_MALFORMED_TIMESTAMP) \
    XX(LS_ERROR_PARSE_UNTIMED_TEXT) \
    XX(LS_ERROR_FORMAT_INVALID_ARGUMENT) \
    XX(LS_ERROR_FORMAT_INVALID_TIMESTAMP) \
    XX(LS_ERROR_FORMAT_TOO_LARGE) \
    XX(LS_ERROR_WRITE_INVALID_ARGUMENT) \
    XX(LS_ERROR_WRITE_INVALID_LINE) \
    XX(LS_ERROR_WRITE_FORMAT_FAILED) \
    XX(LS_ERROR_WRITE_TEMP_PATH_TOO_LONG) \
    XX(LS_ERROR_WRITE_TEMP_OPEN_FAILED) \
    XX(LS_ERROR_WRITE_WRITE_FAILED) \
    XX(LS_ERROR_WRITE_CLOSE_FAILED) \
    XX(LS_ERROR_WRITE_RENAME_FAILED) \
    XX(LS_ERROR_LYRICS_LOAD_INVALID_ARGUMENT) \
    XX(LS_ERROR_LYRICS_LOAD_MISSING_PATH) \
    XX(LS_ERROR_LYRICS_LOAD_OPEN_FAILED) \
    XX(LS_ERROR_LYRICS_LOAD_READ_FAILED) \
    XX(LS_ERROR_LYRICS_LOAD_FILE_TOO_LARGE) \
    XX(LS_ERROR_LYRICS_LOAD_INVALID_UTF8) \
    XX(LS_ERROR_LYRICS_LOAD_EMPTY) \
    XX(LS_ERROR_CTC_ASSETS_INVALID_ARGUMENT) \
    XX(LS_ERROR_CTC_ASSETS_MISSING_MODEL_PATH) \
    XX(LS_ERROR_CTC_ASSETS_MISSING_TOKENIZER_PATH) \
    XX(LS_ERROR_CTC_ASSETS_MODEL_NOT_FOUND) \
    XX(LS_ERROR_CTC_ASSETS_TOKENIZER_NOT_FOUND) \
    XX(LS_ERROR_CTC_AUDIO_INVALID_ARGUMENT) \
    XX(LS_ERROR_CTC_AUDIO_MISSING_PATH) \
    XX(LS_ERROR_CTC_AUDIO_MISSING_FFMPEG) \
    XX(LS_ERROR_CTC_AUDIO_INVALID_SAMPLE_RATE) \
    XX(LS_ERROR_CTC_AUDIO_DECODE_FAILED) \
    XX(LS_ERROR_CTC_AUDIO_EMPTY_AUDIO) \
    XX(LS_ERROR_CTC_AUDIO_NON_FINITE_SAMPLE) \
    XX(LS_ERROR_CTC_MODEL_INPUT_INVALID_ARGUMENT) \
    XX(LS_ERROR_CTC_MODEL_INPUT_INVALID_SAMPLE_RATE) \
    XX(LS_ERROR_CTC_MODEL_INPUT_INVALID_RATIO) \
    XX(LS_ERROR_CTC_MODEL_INPUT_INVALID_WINDOW) \
    XX(LS_ERROR_CTC_MODEL_INPUT_INVALID_CONTEXT) \
    XX(LS_ERROR_CTC_MODEL_INPUT_AUDIO_SAMPLE_RATE) \
    XX(LS_ERROR_CTC_MODEL_INPUT_EMPTY_AUDIO) \
    XX(LS_ERROR_CTC_MODEL_INPUT_NON_FINITE_SAMPLE) \
    XX(LS_ERROR_CTC_MODEL_INPUT_TOO_MANY_SAMPLES) \
    XX(LS_ERROR_CTC_MODEL_INPUT_INVALID_MODEL_IO) \
    XX(LS_ERROR_CTC_INFERENCE_INVALID_ARGUMENT) \
    XX(LS_ERROR_CTC_INFERENCE_INVALID_INPUT) \
    XX(LS_ERROR_CTC_INFERENCE_INVALID_OUTPUT) \
    XX(LS_ERROR_CTC_INFERENCE_OUTPUT_TOO_LARGE) \
    XX(LS_ERROR_CTC_INFERENCE_NON_FINITE_OUTPUT) \
    XX(LS_ERROR_CTC_INFERENCE_INVALID_PROBABILITY) \
    XX(LS_ERROR_CTC_INFERENCE_BACKEND_UNAVAILABLE) \
    XX(LS_ERROR_CTC_INFERENCE_BACKEND_FAILED) \
    XX(LS_ERROR_CTC_INFERENCE_MODEL_LOAD_FAILED) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_ARGUMENT) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_EMISSIONS) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_DIMENSIONS) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_BLANK_TOKEN) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_TARGET_TOKEN) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_TRELLIS) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_PATH) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_TOKEN_SPANS) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_WORD_SPANS) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_TOKENIZED_TEXT) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_NORMALIZED_TEXT) \
    XX(LS_ERROR_CTC_ALIGN_INVALID_FRAME_DURATION) \
    XX(LS_ERROR_CTC_ALIGN_IMPOSSIBLE_ALIGNMENT) \
    XX(LS_ERROR_CTC_ALIGN_TOO_LARGE) \
    XX(LS_ERROR_CTC_TOKENIZE_INVALID_ARGUMENT) \
    XX(LS_ERROR_CTC_TOKENIZE_EMPTY_INPUT) \
    XX(LS_ERROR_CTC_TOKENIZE_TOO_MANY_TOKENS) \
    XX(LS_ERROR_CTC_TOKENIZE_UNSUPPORTED_TOKEN) \
    XX(LS_ERROR_CTC_TOKENIZER_INVALID_ARGUMENT) \
    XX(LS_ERROR_CTC_TOKENIZER_MISSING_PATH) \
    XX(LS_ERROR_CTC_TOKENIZER_OPEN_FAILED) \
    XX(LS_ERROR_CTC_TOKENIZER_READ_FAILED) \
    XX(LS_ERROR_CTC_TOKENIZER_FILE_TOO_LARGE) \
    XX(LS_ERROR_CTC_TOKENIZER_EMPTY) \
    XX(LS_ERROR_CTC_TOKENIZER_INVALID_UTF8) \
    XX(LS_ERROR_CTC_TOKENIZER_EMPTY_TOKEN) \
    XX(LS_ERROR_CTC_TOKENIZER_DUPLICATE_TOKEN) \
    XX(LS_ERROR_CTC_TOKENIZER_MISSING_BLANK) \
    XX(LS_ERROR_CTC_TOKENIZER_TOO_MANY_TOKENS) \
    XX(LS_ERROR_VOCALS_EXTRACT_INVALID_ARGUMENT) \
    XX(LS_ERROR_VOCALS_EXTRACT_MISSING_INPUT) \
    XX(LS_ERROR_VOCALS_EXTRACT_MISSING_OUTPUT) \
    XX(LS_ERROR_VOCALS_EXTRACT_MISSING_MODEL) \
    XX(LS_ERROR_VOCALS_EXTRACT_MISSING_TEMP_DIR) \
    XX(LS_ERROR_VOCALS_EXTRACT_MISSING_FFMPEG) \
    XX(LS_ERROR_VOCALS_EXTRACT_FFMPEG_UNAVAILABLE) \
    XX(LS_ERROR_VOCALS_EXTRACT_INPUT_DECODE_FAILED) \
    XX(LS_ERROR_VOCALS_EXTRACT_MODEL_OPEN_FAILED) \
    XX(LS_ERROR_VOCALS_EXTRACT_STFT_INIT_FAILED) \
    XX(LS_ERROR_VOCALS_EXTRACT_ORT_INIT_FAILED) \
    XX(LS_ERROR_VOCALS_EXTRACT_ORT_MODEL_LOAD_FAILED) \
    XX(LS_ERROR_VOCALS_EXTRACT_UNSUPPORTED_MDX_MODEL) \
    XX(LS_ERROR_VOCALS_EXTRACT_MDX_CONFIG_FAILED) \
    XX(LS_ERROR_VOCALS_EXTRACT_INPUT_READ_FAILED) \
    XX(LS_ERROR_VOCALS_EXTRACT_MDX_PROCESS_FAILED) \
    XX(LS_ERROR_VOCALS_EXTRACT_OUTPUT_WRITE_FAILED) \
    XX(LS_ERROR_PIPELINE_INVALID_ARGUMENT) \
    XX(LS_ERROR_PIPELINE_TEMP_DIR_MISSING) \
    XX(LS_ERROR_PIPELINE_TEMP_PATH_TOO_LONG) \
    XX(LS_ERROR_PIPELINE_TEMP_DIR_CREATE_FAILED) \
    XX(LS_ERROR_PIPELINE_TEMP_CLEANUP_FAILED) \
    XX(LS_ERROR_PIPELINE_VOCALS_ALREADY_AVAILABLE) \
    XX(LS_ERROR_PIPELINE_VOCALS_EXTRACT_FAILED) \
    XX(LS_ERROR_PIPELINE_CTC_ASSETS_INVALID) \
    XX(LS_ERROR_PIPELINE_GENERATE_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_INVALID_ARGUMENT) \
    XX(LS_ERROR_PIPELINE_GENERATE_MISSING_SONG) \
    XX(LS_ERROR_PIPELINE_GENERATE_MISSING_LYRICS) \
    XX(LS_ERROR_PIPELINE_GENERATE_MISSING_OUTPUT) \
    XX(LS_ERROR_PIPELINE_GENERATE_MISSING_VOCALS_MODEL) \
    XX(LS_ERROR_PIPELINE_GENERATE_MISSING_CTC_MODEL) \
    XX(LS_ERROR_PIPELINE_GENERATE_MISSING_TOKENIZER) \
    XX(LS_ERROR_PIPELINE_GENERATE_PREPARE_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_VOCALS_EXTRACT_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_CTC_ASSETS_INVALID) \
    XX(LS_ERROR_PIPELINE_GENERATE_LYRICS_LOAD_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_LYRICS_NORMALIZE_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_TOKENIZER_LOAD_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_TOKENIZE_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_AUDIO_DECODE_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_MODEL_INPUT_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_CTC_MODEL_LOAD_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_CTC_INFERENCE_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_EMISSION_CONVERSION_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_ALIGNMENT_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_OUTPUT_LINES_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_LRC_WRITE_FAILED) \
    XX(LS_ERROR_PIPELINE_GENERATE_TOO_LARGE)
#define XENUMS_NO_TESTS 1
#include "cbase/xenums.c"
#undef XENUMS_NO_TESTS

typedef struct LrcResultHeader {
    enum LsError error;
    char *message;
} LrcResultHeader;

typedef struct LrcPathResultHeader {
    LrcResultHeader header;
    char *path;
} LrcPathResultHeader;

static void
lrc_result_header_init(LrcResultHeader *header) {
    if (header == NULL) {
        return;
    }

    header->error = LS_ERROR_NONE;
    header->message = "ok";

    return;
}

static void
lrc_result_header_set(
    LrcResultHeader *header,
    enum LsError error,
    char *message
) {
    if (header == NULL) {
        return;
    }

    header->error = error;
    header->message = message;

    return;
}

static void
lrc_path_result_header_init(LrcPathResultHeader *header) {
    if (header == NULL) {
        return;
    }

    lrc_result_header_init(&header->header);
    header->path = NULL;

    return;
}

static void
lrc_path_result_header_set(
    LrcPathResultHeader *header,
    enum LsError error,
    char *message,
    char *path
) {
    if (header == NULL) {
        return;
    }

    lrc_result_header_set(&header->header, error, message);
    header->path = path;

    return;
}

#endif /* LS_ERRORS_H */
